//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DictionaryData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictionaryData() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projects.Mvc.Resources.DictionaryData", typeof(DictionaryData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [{ Text: &quot;其他&quot;, Value: &quot;1&quot; },{ Text: &quot;高中&quot;, Value: &quot;2&quot; },{ Text: &quot;本科&quot;, Value: &quot;3&quot; },{ Text: &quot;硕士&quot;, Value: &quot;4&quot; },{ Text: &quot;博士&quot;, Value: &quot;5&quot; }, { Text: &quot;博士后&quot;, Value: &quot;6&quot; }] 的本地化字符串。
        /// </summary>
        internal static string DIC_DATA_DEGREE {
            get {
                return ResourceManager.GetString("DIC_DATA_DEGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{&quot;Text&quot;:&quot;其他&quot;,&quot;Value&quot;:&quot;3&quot;},{&quot;Text&quot;:&quot;女性&quot;,&quot;Value&quot;:&quot;2&quot;},{&quot;Text&quot;:&quot;男性&quot;,&quot;Value&quot;:&quot;1&quot;}] 的本地化字符串。
        /// </summary>
        internal static string DIC_DATA_GENDER {
            get {
                return ResourceManager.GetString("DIC_DATA_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ Text: &quot;未知&quot;, Value: &quot;1&quot; }, { Text: &quot;未婚&quot;, Value: &quot;2&quot; }, { Text: &quot;已婚&quot;, Value: &quot;3&quot; }] 的本地化字符串。
        /// </summary>
        internal static string DIC_DATA_MARRIAGE {
            get {
                return ResourceManager.GetString("DIC_DATA_MARRIAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ Text: &quot;汉族&quot;, Value: &quot;1&quot; },{ Text: &quot;其他族&quot;, Value: &quot;2&quot; },{ Text: &quot;未知&quot;, Value: &quot;3&quot; }] 的本地化字符串。
        /// </summary>
        internal static string DIC_DATA_NATION {
            get {
                return ResourceManager.GetString("DIC_DATA_NATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{Text:&quot;4次&quot;,Value:&quot;4&quot;},{Text:&quot;6次&quot;,Value:&quot;6&quot;}] 的本地化字符串。
        /// </summary>
        internal static string DIC_DATA_SHIFT_DAILY_ATTEND_TIME {
            get {
                return ResourceManager.GetString("DIC_DATA_SHIFT_DAILY_ATTEND_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{Text:&quot;正常&quot;,Value:&quot;0&quot;},{Text:&quot;迟到&quot;,Value:&quot;1&quot;},{Text:&quot;早退&quot;,Value:&quot;2&quot;},{Text:&quot;缺勤半天&quot;,Value:&quot;3&quot;},{Text:&quot;缺勤一天&quot;,Value:&quot;4&quot;},{Text:&quot;异常&quot;,Value:&quot;5&quot;}] 的本地化字符串。
        /// </summary>
        internal static string DIC_DATA_SHIFT_STAUTS {
            get {
                return ResourceManager.GetString("DIC_DATA_SHIFT_STAUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ Text: &quot;总监&quot;, Value: &quot;1&quot; },{ Text: &quot;经理&quot;, Value: &quot;2&quot; },{ Text: &quot;主管&quot;, Value: &quot;3&quot; },{ Text: &quot;职员&quot;, Value: &quot;4&quot; }] 的本地化字符串。
        /// </summary>
        internal static string DIC_DATA_STAFF_POSITION {
            get {
                return ResourceManager.GetString("DIC_DATA_STAFF_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ Text: &quot;初级职称&quot;, Value: &quot;1&quot; },{ Text: &quot;中级职称&quot;, Value: &quot;2&quot; },{ Text: &quot;高级职称&quot;, Value: &quot;3&quot; }] 的本地化字符串。
        /// </summary>
        internal static string DIC_DATA_STAFF_TITLE {
            get {
                return ResourceManager.GetString("DIC_DATA_STAFF_TITLE", resourceCulture);
            }
        }
    }
}
