//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResultMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResultMessage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projects.Mvc.Resources.ResultMessage", typeof(ResultMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 该部门下存在子部门,请先删除所有子部门后再进行移除操作 的本地化字符串。
        /// </summary>
        internal static string BranchHasChildWhenRemove {
            get {
                return ResourceManager.GetString("BranchHasChildWhenRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该部门下存在职员,请将职员都删除后再进行移除操作 的本地化字符串。
        /// </summary>
        internal static string BranchHasStaffWhenRemove {
            get {
                return ResourceManager.GetString("BranchHasStaffWhenRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门不存在 的本地化字符串。
        /// </summary>
        internal static string BranchNotFound {
            get {
                return ResourceManager.GetString("BranchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该部门考勤班次未设置 的本地化字符串。
        /// </summary>
        internal static string BranchShiftNotFound {
            get {
                return ResourceManager.GetString("BranchShiftNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职员信息创建失败,详细信息请参看日志 的本地化字符串。
        /// </summary>
        internal static string CreateStaffFailure {
            get {
                return ResourceManager.GetString("CreateStaffFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职员信息创建成功 的本地化字符串。
        /// </summary>
        internal static string CreateStaffOK {
            get {
                return ResourceManager.GetString("CreateStaffOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建失败 的本地化字符串。
        /// </summary>
        internal static string DbCreateFailure {
            get {
                return ResourceManager.GetString("DbCreateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建成功 的本地化字符串。
        /// </summary>
        internal static string DbCreateSuccess {
            get {
                return ResourceManager.GetString("DbCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        internal static string DbDeleteFailure {
            get {
                return ResourceManager.GetString("DbDeleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string DbDeleteSuccess {
            get {
                return ResourceManager.GetString("DbDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功 的本地化字符串。
        /// </summary>
        internal static string DbUpdateSuccess {
            get {
                return ResourceManager.GetString("DbUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职员信息删除失败 的本地化字符串。
        /// </summary>
        internal static string DeleteStaffFailure {
            get {
                return ResourceManager.GetString("DeleteStaffFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职员信息删除成功 的本地化字符串。
        /// </summary>
        internal static string DeleteStaffOK {
            get {
                return ResourceManager.GetString("DeleteStaffOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本日为公休日 的本地化字符串。
        /// </summary>
        internal static string IsHoliday {
            get {
                return ResourceManager.GetString("IsHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤班次创建失败 的本地化字符串。
        /// </summary>
        internal static string ShiftCreateFailure {
            get {
                return ResourceManager.GetString("ShiftCreateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤班次创建成功 的本地化字符串。
        /// </summary>
        internal static string ShiftCreateOK {
            get {
                return ResourceManager.GetString("ShiftCreateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该考勤班次正在被使用  的本地化字符串。
        /// </summary>
        internal static string ShiftInUse {
            get {
                return ResourceManager.GetString("ShiftInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考勤班次不存在 的本地化字符串。
        /// </summary>
        internal static string ShiftNotFound {
            get {
                return ResourceManager.GetString("ShiftNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职员考勤记录信息创建失败 的本地化字符串。
        /// </summary>
        internal static string StaffAttendanceCreateFailure {
            get {
                return ResourceManager.GetString("StaffAttendanceCreateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职员考勤记录信息创建成功 的本地化字符串。
        /// </summary>
        internal static string StaffAttendanceCreateSuccess {
            get {
                return ResourceManager.GetString("StaffAttendanceCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职员为默认权限,无需特别设置 的本地化字符串。
        /// </summary>
        internal static string StaffAuthorizedNotNeed {
            get {
                return ResourceManager.GetString("StaffAuthorizedNotNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职员登录成功 的本地化字符串。
        /// </summary>
        internal static string StaffLoginSuccess {
            get {
                return ResourceManager.GetString("StaffLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职员信息不存在,请检查职员姓名(工号)和密码是否错误 的本地化字符串。
        /// </summary>
        internal static string StaffNotFound {
            get {
                return ResourceManager.GetString("StaffNotFound", resourceCulture);
            }
        }
    }
}
