//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebUIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebUIResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projects.Mvc.Resources.WebUIResource", typeof(WebUIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string COL_COMMON_OPERATE {
            get {
                return ResourceManager.GetString("COL_COMMON_OPERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志编号 的本地化字符串。
        /// </summary>
        internal static string COL_LOG_ID {
            get {
                return ResourceManager.GetString("COL_LOG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志消息 的本地化字符串。
        /// </summary>
        internal static string COL_LOG_MESSAGE {
            get {
                return ResourceManager.GetString("COL_LOG_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录者 的本地化字符串。
        /// </summary>
        internal static string COL_LOG_NAME {
            get {
                return ResourceManager.GetString("COL_LOG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志时间 的本地化字符串。
        /// </summary>
        internal static string COL_LOG_TIME {
            get {
                return ResourceManager.GetString("COL_LOG_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志类型 的本地化字符串。
        /// </summary>
        internal static string COL_LOG_TYPE {
            get {
                return ResourceManager.GetString("COL_LOG_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        internal static string COL_STAFF_AUTHORIZED {
            get {
                return ResourceManager.GetString("COL_STAFF_AUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属部门 的本地化字符串。
        /// </summary>
        internal static string COL_STAFF_BRANCH {
            get {
                return ResourceManager.GetString("COL_STAFF_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        internal static string COL_STAFF_GERDEN {
            get {
                return ResourceManager.GetString("COL_STAFF_GERDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证号码 的本地化字符串。
        /// </summary>
        internal static string COL_STAFF_IDCARD {
            get {
                return ResourceManager.GetString("COL_STAFF_IDCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入职时间 的本地化字符串。
        /// </summary>
        internal static string COL_STAFF_JOIN_JOB {
            get {
                return ResourceManager.GetString("COL_STAFF_JOIN_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码 的本地化字符串。
        /// </summary>
        internal static string COL_STAFF_MOBILE {
            get {
                return ResourceManager.GetString("COL_STAFF_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职员姓名 的本地化字符串。
        /// </summary>
        internal static string COL_STAFF_NAME {
            get {
                return ResourceManager.GetString("COL_STAFF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工号 的本地化字符串。
        /// </summary>
        internal static string COL_STAFF_NUM {
            get {
                return ResourceManager.GetString("COL_STAFF_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位 的本地化字符串。
        /// </summary>
        internal static string COL_STAFF_POSITION {
            get {
                return ResourceManager.GetString("COL_STAFF_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束日期 的本地化字符串。
        /// </summary>
        internal static string COL_VACATION_END_DATE {
            get {
                return ResourceManager.GetString("COL_VACATION_END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节假日ID 的本地化字符串。
        /// </summary>
        internal static string COL_VACATION_ID {
            get {
                return ResourceManager.GetString("COL_VACATION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节假日名称 的本地化字符串。
        /// </summary>
        internal static string COL_VACATION_NAME {
            get {
                return ResourceManager.GetString("COL_VACATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        internal static string COL_VACATION_START_DATE {
            get {
                return ResourceManager.GetString("COL_VACATION_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string COMMON_NEXT_PAGE {
            get {
                return ResourceManager.GetString("COMMON_NEXT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录 的本地化字符串。
        /// </summary>
        internal static string COMMON_PAGE_RECORD {
            get {
                return ResourceManager.GetString("COMMON_PAGE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        internal static string COMMON_PAGE_SIZE {
            get {
                return ResourceManager.GetString("COMMON_PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        internal static string COMMON_PREV_PAGE {
            get {
                return ResourceManager.GetString("COMMON_PREV_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的生日信息 的本地化字符串。
        /// </summary>
        internal static string ERROR_TEXT_BIRTHDAY {
            get {
                return ResourceManager.GetString("ERROR_TEXT_BIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的毕业日期信息 的本地化字符串。
        /// </summary>
        internal static string ERROR_TEXT_GRADUATE_DATE {
            get {
                return ResourceManager.GetString("ERROR_TEXT_GRADUATE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的入职日期 的本地化字符串。
        /// </summary>
        internal static string ERROR_TEXT_JOIN_DATE {
            get {
                return ResourceManager.GetString("ERROR_TEXT_JOIN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不正确的手机号码格式 的本地化字符串。
        /// </summary>
        internal static string ERROR_TEXT_MOBILE {
            get {
                return ResourceManager.GetString("ERROR_TEXT_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不正确的密码格式 的本地化字符串。
        /// </summary>
        internal static string ERROR_TEXT_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_TEXT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入家庭住址 的本地化字符串。
        /// </summary>
        internal static string NULL_TEXT_ADDRESS {
            get {
                return ResourceManager.GetString("NULL_TEXT_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择毕业学校 的本地化字符串。
        /// </summary>
        internal static string NULL_TEXT_GRADUATE_DATE {
            get {
                return ResourceManager.GetString("NULL_TEXT_GRADUATE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入毕业学校 的本地化字符串。
        /// </summary>
        internal static string NULL_TEXT_GRADUATE_SCHOOL {
            get {
                return ResourceManager.GetString("NULL_TEXT_GRADUATE_SCHOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入身份证号码 的本地化字符串。
        /// </summary>
        internal static string NULL_TEXT_IDCARD {
            get {
                return ResourceManager.GetString("NULL_TEXT_IDCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入手机号码 的本地化字符串。
        /// </summary>
        internal static string NULL_TEXT_MOBILE {
            get {
                return ResourceManager.GetString("NULL_TEXT_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入备注信息 的本地化字符串。
        /// </summary>
        internal static string NULL_TEXT_NOTE {
            get {
                return ResourceManager.GetString("NULL_TEXT_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入姓名 的本地化字符串。
        /// </summary>
        internal static string NULL_TEXT_STAFF_NAME {
            get {
                return ResourceManager.GetString("NULL_TEXT_STAFF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入8位工号 的本地化字符串。
        /// </summary>
        internal static string NULL_TEXT_STAFF_NUM {
            get {
                return ResourceManager.GetString("NULL_TEXT_STAFF_NUM", resourceCulture);
            }
        }
    }
}
